# Python Review 

Short review about some core concepts in Python exempolified by objects in the NumPy library. Goals:

- recall basic Python vocabulary
- practice markdown syntax

## Libraries and Packges
**library:** is a collection of the code that we can use to perform specific tasks in our programs. It can be a single file or multiple files.

**NumPy:**

- core library for numerical computing in Python
- many of libraries us NumPy arrays as their building blocks
- computations on NumPy objects are optimized for speed and memory usage

Let's import NumPy with its **standard abbreviations** `np`:

In [1]:
import numpy as np

(esc + press M -> convert code to markdown cell)

## Variables
**Variable:** a name we assign to a particular object in Python

Example:

In [2]:
# Assign a small array to variable a
a = np.array([[1,1,2],[3,5,8]])

To view a variable's value from our Jupyter notebook:

In [3]:
# Show the value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Print the value 
print(a)

[[1 1 2]
 [3 5 8]]
